import 'dart:io';

import 'package:jnigen/jnigen.dart';

void main(List<String> args) {
  // Get the project root directory (where pubspec.yaml is located)
  final packageRoot = Directory.current.uri;
  generateJniBindings(
    Config(
      outputConfig: OutputConfig(
        dartConfig: DartCodeOutputConfig(
          path: packageRoot.resolve('lib/src/generated/battery_info_jni.dart'),
          structure: OutputStructure.singleFile,
        ),
      ),
      androidSdkConfig: AndroidSdkConfig(
        addGradleDeps: true,
        androidExample: 'example',
      ),
      sourcePath: [packageRoot.resolve('android/src/main/java')],
      classes: [
        'com.example.battery_info_example.BatteryInfoJni',
        'com.example.battery_info_example.NetworkClient',
      ],
      preamble: '''
// Auto-generated by jnigen
// Generated bindings for BatteryInfoJni and NetworkClient
''',
    ),
  );
}
